# API 配置
api_prefix: /api/v2

apis:
  beatmap_scores: /beatmaps/{beatmap_id}/scores/users/{user_id}
  beatmap_best_scores: /beatmaps/{beatmap_id}/scores/users/{user_id}
  beatmap_all_scores: /beatmaps/{beatmap_id}/scores/users/{user_id}/all
  user_info: /users/{user_id}
  batch_user_info: /users/{user_id}
  oauth_token: /oauth/token
  beatmap_info: /beatmaps/{beatmap_id}
  user_scores: /users/{user_id}/scores/{type}
